apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.serviceName }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zayatihamza/online-boutique-gitops
    targetRevision: main
    path: manifests/${{ values.serviceName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
