apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  description: "Microservice ${{ values.serviceName }} onboardé via self-service RHDH"
  annotations:
    argocd/app-name: ${{ values.serviceName }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
  tags:
    - onboarded
    - online-boutique
spec:
  type: service
  lifecycle: production
  owner: team-online-boutique
  system: online-boutique
