apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shoppingassistantservice
  annotations:
    github.com/project-slug: https://github.com/zayatihamza/microservices-demo
spec:
  type: service
  owner: platform-team
  lifecycle: production
  system: online-boutique
