apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.SERVICE_NAME}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zayatihamza/online-boutique-gitops
    targetRevision: main
    path: manifests/${{values.SERVICE_NAME}}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.NAMESPACE}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
