apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboard-existing-microservice
  title: Onboard Existing Microservice
  description: Onboard an existing Online Boutique microservice into the platform (webhook, ArgoCD app, pipeline run, catalog entry).
spec:
  owner: platform-team
  type: service
  parameters:
    - title: Service info
      required: [serviceName, owner, repo]
      properties:
        serviceName:
          title: Service name
          type: string
        owner:
          title: GitHub org/owner
          type: string
        repo:
          title: GitHub repo name
          type: string
        namespace:
          title: Target namespace
          type: string
          default: default

  steps:
    - id: create-webhook
      name: Create GitHub webhook
      action: github:webhook
      input:
        repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}"
        webhookUrl: https://whomever-life-tacking.ngrok-free.dev/webhook/generic
        webhookSecret: ${{ secrets.githubWebhookSecret }}
        events: ["push"]
        contentType: json

    - id: create-argocd-app
      name: Create ArgoCD Application
      action: http:backstage:request
      input:
        method: POST
        path: /proxy/k8s-api/apis/argoproj.io/v1alpha1/namespaces/argocd/applications
        headers:
          Content-Type: application/json
        body:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{ parameters.serviceName }}
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/zayatihamza/online-boutique-gitops
              targetRevision: main
              path: manifests/${{ parameters.serviceName }}
            destination:
              server: https://kubernetes.default.svc
              namespace: ${{ parameters.namespace }}
            syncPolicy:
              automated:
                selfHeal: true
                prune: true
              syncOptions:
                - CreateNamespace=true

    - id: trigger-first-pipelinerun
      name: Trigger initial build PipelineRun
      action: http:backstage:request
      input:
        method: POST
        path: /proxy/k8s-api/apis/tekton.dev/v1/namespaces/cicd/pipelineruns
        headers:
          Content-Type: application/json
        body:
          apiVersion: tekton.dev/v1
          kind: PipelineRun
          metadata:
            generateName: microservice-pipeline-run-onboard-
            namespace: cicd
          spec:
            pipelineRef:
              name: microservice-pipeline-generic
            taskRunTemplate:
              serviceAccountName: pipeline-sa
            params:
              - name: SERVICENAME
                value: "${{ parameters.serviceName }}"
              - name: GITREPOURL
                value: "https://github.com/${{ parameters.owner }}/${{ parameters.repo }}"
              - name: GITREVISION
                value: "main"
              - name: IMAGENAME
                value: "image-registry.openshift-image-registry.svc:5000/cicd/${{ parameters.serviceName }}"
              - name: SONARHOSTURL
                value: "http://sonarqube-sonarqube.sonarqube.svc:9000"
              - name: SONARPROJECTKEY
                value: "${{ parameters.serviceName }}"
              - name: SONARTOKEN
                value: "sqa_e3e738aeb2e6c535d74e9093e7455678e8f76d5f"
              - name: GITOPSREPOURL
                value: "https://github.com/zayatihamza/online-boutique-gitops"
              - name: NAMESPACE
                value: "${{ parameters.namespace }}"
            workspaces:
              - name: shared-workspace
                volumeClaimTemplate:
                  spec:
                    accessModes: [ReadWriteOnce]
                    resources: {requests: {storage: 1Gi}}
                    storageClassName: thin-csi
              - name: gitops-workspace
                volumeClaimTemplate:
                  spec:
                    accessModes: [ReadWriteOnce]
                    resources: {requests: {storage: 500Mi}}
                    storageClassName: thin-csi

    - id: fetch-catalog-skeleton
      name: Generate catalog files
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./catalog-output
        values:
          serviceName: ${{ parameters.serviceName }}
          owner: ${{ parameters.owner }}
          repo: ${{ parameters.repo }}
          namespace: ${{ parameters.namespace }}

    - id: publish-catalog-info
      name: Publish catalog files to platform-catalog
      action: publish:github
      input:
        repoUrl: github.com?owner=zayatihamza&repo=platform-catalog
        title: "Add ${{ parameters.serviceName }} to catalog"
        description: "Auto-generated by onboarding template"
        defaultBranch: main
        sourcePath: ./catalog-output
        targetPath: resources/services/${{ parameters.serviceName }}
        requireCodeOwnerReview: false

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-catalog-info'].output.repoContentsUrl }}
        catalogInfoPath: '/resources/services/${{ parameters.serviceName }}/catalog-info.yaml'

  output:
    links:
      - title: View in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
