apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboard-existing-microservice
  title: Onboard Existing Microservice
spec:
  owner: platform-team
  type: service
  parameters:
    - title: Service info
      required: [serviceName, owner, repo]
      properties:
        serviceName:
          type: string
        owner:
          type: string
        repo:
          type: string
        namespace:
          type: string
          default: default
    - title: Authentication
      required: [k8sToken]
      properties:
        k8sToken:
          type: string
          ui:field: Secret
          ui:widget: password
          description: "Token du ServiceAccount pipeline-sa (contenu de rhdh-sa-token.txt)"

  steps:
    - id: create-webhook
      name: Create GitHub webhook
      action: github:webhook
      input:
        repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}"
        webhookUrl: https://whomever-life-tacking.ngrok-free.dev/webhook/generic
        webhookSecret: ${{ secrets.githubWebhookSecret }}
        events: ["push"]
        contentType: json

    - id: create-argocd-app
      name: Create ArgoCD Application
      action: http:backstage:request
      input:
        method: POST
        path: https://api.okd.3s.lab:6443/apis/argoproj.io/v1alpha1/namespaces/argocd/applications
        headers:
          Authorization: Bearer ${{ secrets.k8sToken }}
          Content-Type: application/json
        body:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{ parameters.serviceName }}
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/zayatihamza/online-boutique-gitops
              targetRevision: main
              path: manifests/${{ parameters.serviceName }}
            destination:
              server: https://kubernetes.default.svc
              namespace: ${{ parameters.namespace }}
            syncPolicy:
              automated:
                selfHeal: true
                prune: true
              syncOptions:
                - CreateNamespace=true

    - id: trigger-first-pipelinerun
      name: Trigger initial build PipelineRun
      action: http:backstage:request
      input:
        method: POST
        path: https://api.okd.3s.lab:6443/apis/tekton.dev/v1/namespaces/cicd/pipelineruns
        headers:
          Authorization: Bearer ${{ secrets.k8sToken }}
          Content-Type: application/json
        body:
          apiVersion: tekton.dev/v1
          kind: PipelineRun
          metadata:
            generateName: microservice-pipeline-run-onboard-
            namespace: cicd
          spec:
            pipelineRef:
              name: microservice-pipeline-generic
            taskRunTemplate:
              serviceAccountName: pipeline-sa
            params:
              - {name: SERVICENAME, value: "${{ parameters.serviceName }}"}
              - {name: GITREPOURL, value: "https://github.com/${{ parameters.owner }}/${{ parameters.repo }}"}
              - {name: GITREVISION, value: "main"}
              - {name: IMAGENAME, value: "image-registry.openshift-image-registry.svc:5000/cicd/${{ parameters.serviceName }}"}
              - {name: SONARHOSTURL, value: "http://sonarqube-sonarqube.sonarqube.svc:9000"}
              - {name: SONARPROJECTKEY, value: "${{ parameters.serviceName }}"}
              - {name: SONARTOKEN, value: "${{ secrets.sonarToken }}"}
              - {name: GITOPSREPOURL, value: "https://github.com/zayatihamza/online-boutique-gitops"}
              - {name: NAMESPACE, value: "${{ parameters.namespace }}"}
            workspaces:
              - name: shared-workspace
                volumeClaimTemplate:
                  spec:
                    accessModes: [ReadWriteOnce]
                    resources: {requests: {storage: 1Gi}}
                    storageClassName: thin-csi
              - name: gitops-workspace
                volumeClaimTemplate:
                  spec:
                    accessModes: [ReadWriteOnce]
                    resources: {requests: {storage: 500Mi}}
                    storageClassName: thin-csi
